baseURL = 'https://jheronimus.github.io/mrbios/'
relativeURLs = false
canonifyURLs = false
locale = 'en-us'
title = 'MR BIOS Archive'
dataDir = '../data'
disableKinds = ['taxonomy', 'term']

[params]
  githubRepo = 'jheronimus/mrbios'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
